import ComponentActionbar from './Actionbar';
import ComponentButton from './Button';
import ComponentConclusionBar from './ConclusionBar';
import ComponentField from './Form/Field';
import ComponentFilter from './Filter';
import ComponentModal from './Modal';
import ComponentPage from './Page';
import ComponentPageHeader from './PageHeader';
import ComponentStatus from './Status';
import ComponentTable from './Table';
import ComponentTabs from './Tabs';

export const Actionbar = ComponentActionbar;
export const Button = ComponentButton;
export const ConclusionBar = ComponentConclusionBar;
export const Field = ComponentField;
export const Filter = ComponentFilter;
export const Modal = ComponentModal;
export const Page = ComponentPage;
export const PageHeader = ComponentPageHeader;
export const Status = ComponentStatus;
export const Table = ComponentTable;
export const Tabs = ComponentTabs;
